name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      old_version:
        description: 'Last version number (e.g. 1.6.2)'
        required: true
      new_version:
        description: 'New version number (e.g. 1.6.3)'
        required: true
      snapshot_version:
        description: 'Next snapshot version (e.g. 1.6.4-snapshot)'
        required: true

jobs:
  prepare_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set git user information
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Fetch develop branch
        run: git fetch origin develop

      - name: Create release branch
        run: |
          git checkout develop
          git pull origin develop
          git checkout -b "release/v${{ inputs.new_version }}"
          git push origin "release/v${{ inputs.new_version }}"

      - name: Update version number in README.md
        run: |
          sed -i 's/Current version: v[0-9]\+\(\.[0-9]\+\)\{2\}\(-[a-zA-Z0-9]\+\)\{0,1\}/Current version: v${{ inputs.new_version }}/g' README.md
          git add README.md
          git commit -m "Release v${{ inputs.new_version }}"
          git push origin "release/v${{ inputs.new_version }}"

      - name: Update version number in package.json and package-lock.json
        run: |
          npm version "${{ inputs.new_version }}" --allow-same-version --message "Release v%s"
          git push origin "release/v${{ inputs.new_version }}"

      - name: Create PHP Migration File
        run: |
          timestamp=$(date +'%Y%m%d%H%M%S')
          migration_file="./migrations/Version${timestamp}.php"
          echo "<?php 
          
          declare(strict_types=1);

          namespace DoctrineMigrations;
          
          use Doctrine\DBAL\Schema\Schema;
          use Doctrine\Migrations\AbstractMigration;
          
          final class Version${timestamp} extends AbstractMigration
          {
            public function getDescription(): string
              {
                return '';
              }
          
            public function up(Schema \$schema): void
              {
                // this up() migration is auto-generated, please modify it to your needs
                \$this->addSql('UPDATE installation_status SET version = \'v${{ inputs.new_version }}\' WHERE id = 1');
              }
          
            public function down(Schema \$schema): void
              {
                // this down() migration is auto-generated, please modify it to your needs
                \$this->addSql('UPDATE installation_status SET version = \'v${{ inputs.old_version }}\' WHERE id = 1');
              }
          }" > "${migration_file}"
          git add "./migrations/Version${timestamp}.php"
          git commit -m "Release v${{ inputs.new_version }}"
          git push origin "release/v${{ inputs.new_version }}"
  
  create_pull_requests:
    needs: prepare_release_branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set git user information
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Wait
        run: sleep 10s

      - name: Fetch release branch
        run: git fetch origin "release/v${{ inputs.new_version }}" --depth=1

      - name: Create pull request from release branch to master
        run: |
          gh pr create --base master --head "release/v${{ inputs.new_version }}" --title "v${{ inputs.new_version }} --> master" --body "Automated PR creation for release v${{ inputs.new_version }}"
          gh pr merge "release/v${{ inputs.new_version }}" --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request from master to develop
        run: |
          gh pr create --base develop --head "master" --title "master --> develop" --body "Automated PR creation for release v${{ inputs.new_version }}"
          gh pr merge "master" --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prepare_snapshot_version:
    needs: create_pull_requests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set git user information
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Fetch develop branch
        run: |
          git fetch origin develop
          git checkout develop
          git pull origin develop

      - name: Update version number in README.md
        run: |
          sed -i 's/Current version: v[0-9]\+\(\.[0-9]\+\)\{2\}\(-[a-zA-Z0-9]\+\)\{0,1\}/Current version: v${{ inputs.snapshot_version }}/g' README.md
          git add README.md
          git commit -m "Snapshot v${{ inputs.snapshot_version }}"
          git push origin develop

      - name: Update version number in package.json and package-lock.json
        run: |
          npm version "${{ inputs.snapshot_version }}" --allow-same-version --message "Snapshot v%s"
          git push origin develop

      - name: Create PHP Migration File
        run: |
          timestamp=$(date +'%Y%m%d%H%M%S')
          migration_file="./migrations/Version${timestamp}.php"
          echo "<?php 
          
          declare(strict_types=1);

          namespace DoctrineMigrations;
          
          use Doctrine\DBAL\Schema\Schema;
          use Doctrine\Migrations\AbstractMigration;
          
          final class Version${timestamp} extends AbstractMigration
          {
            public function getDescription(): string
              {
                return '';
              }
          
            public function up(Schema \$schema): void
              {
                // this up() migration is auto-generated, please modify it to your needs
                \$this->addSql('UPDATE installation_status SET version = \'v${{ inputs.snapshot_version }}\' WHERE id = 1');
              }
          
            public function down(Schema \$schema): void
              {
                // this down() migration is auto-generated, please modify it to your needs
                \$this->addSql('UPDATE installation_status SET version = \'v${{ inputs.new_version }}\' WHERE id = 1');
              }
          }" > "${migration_file}"
          git add "./migrations/Version${timestamp}.php"
          git commit -m "Snapshot v${{ inputs.snapshot_version }}"
          git push origin develop
